 services:

  postgresql:
    image: postgres:14-alpine
    container_name: quest_data_service
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quest_data
      - PGDATA=/data/postgres





  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data



#  app:
#    build: .
#    container_name: quest-app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    depends_on:
#      - redis

 volumes:
   redis_data: